version: '3.3'
services:
  node_basic:
    image: gmoralesc/node_basic
    build: .
    ports:
      - 3000:3000
    volumes:
    - type: bind
      source: .
        target: usr/src/app
      - /usr/src/app/node_modules
